title: "SOL3000 - Diseño y Análisis de la Investigación Social"
author: "Pia Carozzi"
description: "Ayudantía"
lang: "es"

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%b %d, %y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

# Theme settings
dark_theme: false            # use the dark mode as default
dark_header: true           # keep the header dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # (optional) site navigation in the header
# - index.html
  - README.md
# - Programa: "https://"       # linking external sites is also supported

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:pjcarozzi@uc.cl"
  github: "https://github.com/pjcarozzi/SOL3000_19"
  rss: "/SOL3000_19/feed.xml"

# Pagination
show_excerpts: false         # preview articles on the home page
paginate: 10                  # number of articles per page
excerpt_separator: "\n\n\n"  # indicate the end of the excerpt by two blank lines

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
